[Settings]
ID = "b08e75f8-6b2c-47b1-a6f6-46aa3e8c06b7"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "testnet/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "testnet/build/"
  # This will be your default build command
  command = "yarn build"
